language: r
sudo: false
cache: packages

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"

repos:
  XRAN: https://xran.yihui.org

before_install:
  - "curl https://xran.yihui.org/.gitconfig -o ~/.gitconfig"

after_success:
  - "(curl https://xran.yihui.org/r-xran | bash)"
